
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int cadena = 2;
  public static final int especial = 24;
  public static final int coma = 17;
  public static final int flecha = 8;
  public static final int conjj = 16;
  public static final int letraexp = 3;
  public static final int porcentaje = 12;
  public static final int llaveI = 4;
  public static final int guion = 7;
  public static final int punto = 10;
  public static final int ptcoma = 9;
  public static final int dospt = 6;
  public static final int interrog = 15;
  public static final int llaveC = 5;
  public static final int EOF = 0;
  public static final int letra = 20;
  public static final int id = 18;
  public static final int error = 1;
  public static final int orchar = 11;
  public static final int caso3 = 23;
  public static final int asterisco = 14;
  public static final int caso2 = 22;
  public static final int dig = 19;
  public static final int mas = 13;
  public static final int caso1 = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "cadena",
  "letraexp",
  "llaveI",
  "llaveC",
  "dospt",
  "guion",
  "flecha",
  "ptcoma",
  "punto",
  "orchar",
  "porcentaje",
  "mas",
  "asterisco",
  "interrog",
  "conjj",
  "coma",
  "id",
  "dig",
  "letra",
  "caso1",
  "caso2",
  "caso3",
  "especial"
  };
}

